/**
 * generated by HARMLESS : 'Hardware ARchitecture Modeling Language
 *                          for Embedded Software Simulation'
 * model : e200z4
 *
 */

#ifndef __TIMING_mem_H__
#define __TIMING_mem_H__

#include <iostream>
#include "timingBase.h"
#include "types.h"
#include "fifo.h"

class arch;

class timingmem : public timingBase {

	const unsigned int m_inOffset;
	const unsigned int m_outOffset;
	//declare simulation steps
	bool step_0(arch *);
	bool step_1(arch *);
	bool step_2(arch *);
	typedef bool (timingmem::* stepPtr)(arch *);
	stepPtr nextStep; //points to the next step
	fifo<u32> *m_accessFifo;
	public:
	timingmem(const unsigned int inOffset, const unsigned int outOffset) : 
	m_inOffset(inOffset), m_outOffset(outOffset) {init();};
	virtual void run(arch *arch) {
		while((this->*nextStep)(arch));
	}
	virtual void init() {
		nextStep = &timingmem::step_0;
		m_accessFifo = new fifo<u32>("timing mem fifo",16); //arbitrary max val
	};
	bool isInit() {return nextStep == &timingmem::step_0;};
	virtual std::string toString() {return std::string("timingmem");};
	void insertInDataCacheFifo(const u32 addr)
	{
		m_accessFifo->write(addr);
	}	
};
#endif // __TIMING_mem_H__
