/**
 * generated by HARMLESS : 'Hardware ARchitecture Modeling Language
 *                          for Embedded Software Simulation'
 * model : e200z4
 *
 */

#include "instruction.h" //first for precompiled headers
#include <stdio.h>
#include "macro.h"
#include "utils.h"

//instructions with a mnemo.
const char* const e200z4_SP_Check_abs_bc_bi_bo_d_revStatPred_t_tolr_updatelr_z::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"+");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_d_revStatPred_t_tolr_updatelr_z)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_d_f_revStatPred_tolr_updatelr_z::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"+");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_d_f_revStatPred_tolr_updatelr_z)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_d_noCond_revStatPred_tolr_updatelr_z::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"+");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_d_noCond_revStatPred_tolr_updatelr_z)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_nd_noCond_revStatPred_tolr_updatelr::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"+");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_nd_noCond_revStatPred_tolr_updatelr)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_nd_revStatPred_t_tolr_updatelr::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"+");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_nd_revStatPred_t_tolr_updatelr)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_f_nd_revStatPred_tolr_updatelr::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"+");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_f_nd_revStatPred_tolr_updatelr)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_d_nz_statPred_t_tolr_updatelr::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"-");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_d_nz_statPred_t_tolr_updatelr)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_d_f_nz_statPred_tolr_updatelr::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"-");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_d_f_nz_statPred_tolr_updatelr)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_d_noCond_nz_statPred_tolr_updatelr::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"-");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_d_noCond_nz_statPred_tolr_updatelr)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_d_statPred_t_tolr_updatelr_z::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"-");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_d_statPred_t_tolr_updatelr_z)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_d_f_statPred_tolr_updatelr_z::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"-");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_d_f_statPred_tolr_updatelr_z)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_d_noCond_statPred_tolr_updatelr_z::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"-");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_d_noCond_statPred_tolr_updatelr_z)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_nd_noCond_statPred_tolr_updatelr::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"-");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_nd_noCond_statPred_tolr_updatelr)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_nd_statPred_t_tolr_updatelr::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"-");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_nd_statPred_t_tolr_updatelr)");
	#endif
	return result;
}

const char* const e200z4_SP_Check_abs_bc_bi_bo_f_nd_statPred_tolr_updatelr::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"b");
	index += sprintf (result + index,"clrl");
	index += sprintf (result + index,"-");
	index += sprintf (result + index," %u,",(u32)((u32)(BI)));
	if(((FIELD(BI,(4U),(2U)))!=(0U))){
		index += sprintf (result + index,"4*cr%u+",(u32)((u32)(FIELD(BI,(4U),(2U)))));
	}
	if(((FIELD(BI,(1U),(0U)))==(0U))){
		index += sprintf (result + index,"lt");
	}else if(((FIELD(BI,(1U),(0U)))==(1U))){
		index += sprintf (result + index,"gt");
	}else if(((FIELD(BI,(1U),(0U)))==(2U))){
		index += sprintf (result + index,"eq");
	}else if(((FIELD(BI,(1U),(0U)))==(3U))){
		index += sprintf (result + index,"so");
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_SP_Check_abs_bc_bi_bo_f_nd_statPred_tolr_updatelr)");
	#endif
	return result;
}

const char* const e200z4_crba_crbb_crbd_creqv::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((((crbD)==(crbA)))&&(((crbA)==(crbB))))){
		index += sprintf (result + index,"crset ");
		if(((((crbD)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbD)>>((u8)(2U))))));
		}
		if(((FIELD(crbD,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbD,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbD,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbD,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
	}else{
		index += sprintf (result + index,"creqv ");
		if(((((crbD)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbD)>>((u8)(2U))))));
		}
		if(((FIELD(crbD,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbD,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbD,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbD,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbA)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbA)>>((u8)(2U))))));
		}
		if(((FIELD(crbA,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbA,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbA,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbA,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbB)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbB)>>((u8)(2U))))));
		}
		if(((FIELD(crbB,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbB,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbB,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbB,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_crba_crbb_crbd_creqv)");
	#endif
	return result;
}

const char* const e200z4_crba_crbb_crbd_crnor::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((crbA)==(crbB))){
		index += sprintf (result + index,"crnot ");
		if(((((crbD)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbD)>>((u8)(2U))))));
		}
		if(((FIELD(crbD,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbD,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbD,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbD,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbA)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbA)>>((u8)(2U))))));
		}
		if(((FIELD(crbA,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbA,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbA,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbA,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
	}else{
		index += sprintf (result + index,"crnor ");
		if(((((crbD)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbD)>>((u8)(2U))))));
		}
		if(((FIELD(crbD,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbD,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbD,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbD,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbA)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbA)>>((u8)(2U))))));
		}
		if(((FIELD(crbA,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbA,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbA,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbA,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbB)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbB)>>((u8)(2U))))));
		}
		if(((FIELD(crbB,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbB,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbB,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbB,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_crba_crbb_crbd_crnor)");
	#endif
	return result;
}

const char* const e200z4_crba_crbb_crbd_cror::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((crbA)==(crbB))){
		index += sprintf (result + index,"crmove ");
		if(((((crbD)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbD)>>((u8)(2U))))));
		}
		if(((FIELD(crbD,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbD,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbD,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbD,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbA)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbA)>>((u8)(2U))))));
		}
		if(((FIELD(crbA,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbA,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbA,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbA,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
	}else{
		index += sprintf (result + index,"cror ");
		if(((((crbD)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbD)>>((u8)(2U))))));
		}
		if(((FIELD(crbD,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbD,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbD,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbD,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbA)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbA)>>((u8)(2U))))));
		}
		if(((FIELD(crbA,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbA,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbA,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbA,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbB)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbB)>>((u8)(2U))))));
		}
		if(((FIELD(crbB,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbB,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbB,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbB,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_crba_crbb_crbd_cror)");
	#endif
	return result;
}

const char* const e200z4_crba_crbb_crbd_crxor::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((((crbD)==(crbA)))&&(((crbA)==(crbB))))){
		index += sprintf (result + index,"crclr ");
		if(((((crbD)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbD)>>((u8)(2U))))));
		}
		if(((FIELD(crbD,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbD,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbD,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbD,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
	}else{
		index += sprintf (result + index,"crxor ");
		if(((((crbD)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbD)>>((u8)(2U))))));
		}
		if(((FIELD(crbD,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbD,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbD,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbD,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbA)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbA)>>((u8)(2U))))));
		}
		if(((FIELD(crbA,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbA,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbA,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbA,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
		index += sprintf (result + index,",");
		if(((((crbB)>>((u8)(2U))))!=(0U))){
			index += sprintf (result + index,"4*cr%u+",(u32)((u32)(((crbB)>>((u8)(2U))))));
		}
		if(((FIELD(crbB,(1U),(0U)))==(0U))){
			index += sprintf (result + index,"lt");
		}else if(((FIELD(crbB,(1U),(0U)))==(1U))){
			index += sprintf (result + index,"gt");
		}else if(((FIELD(crbB,(1U),(0U)))==(2U))){
			index += sprintf (result + index,"eq");
		}else if(((FIELD(crbB,(1U),(0U)))==(3U))){
			index += sprintf (result + index,"so");
		}
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_crba_crbb_crbd_crxor)");
	#endif
	return result;
}

const char* const e200z4_mb_me_noStatus_ra_rlwinm_rs_sh::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((((MB)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"rotlwi");
	}else if(((((SH)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"clrlwi");
	}else{
		index += sprintf (result + index,"rlwinm");
	}
	index += sprintf (result + index," ");
	if(((((MB)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"r%u,r%u,%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(SH)));
	}else if(((((SH)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"r%u,r%u,%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(MB)));
	}else{
		index += sprintf (result + index,"r%u,r%u,%u,%u,%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(SH)),(u32)((u32)(MB)),(u32)((u32)(ME)));
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_mb_me_noStatus_ra_rlwinm_rs_sh)");
	#endif
	return result;
}

const char* const e200z4_mb_me_ra_rlwinm_rs_sh_useStatus::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((((MB)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"rotlwi");
	}else if(((((SH)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"clrlwi");
	}else{
		index += sprintf (result + index,"rlwinm");
	}
	index += sprintf (result + index,".");
	index += sprintf (result + index," ");
	if(((((MB)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"r%u,r%u,%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(SH)));
	}else if(((((SH)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"r%u,r%u,%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(MB)));
	}else{
		index += sprintf (result + index,"r%u,r%u,%u,%u,%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(SH)),(u32)((u32)(MB)),(u32)((u32)(ME)));
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_mb_me_ra_rlwinm_rs_sh_useStatus)");
	#endif
	return result;
}

const char* const e200z4_mb_me_noStatus_ra_rb_rlwnm_rs::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((((MB)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"rotlw");
	}else{
		index += sprintf (result + index,"rlwnm");
	}
	index += sprintf (result + index," ");
	if(((((MB)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"r%u,r%u,r%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(rB)));
	}else{
		index += sprintf (result + index,"r%u,r%u,r%u,%u,%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(rB)),(u32)((u32)(MB)),(u32)((u32)(ME)));
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_mb_me_noStatus_ra_rb_rlwnm_rs)");
	#endif
	return result;
}

const char* const e200z4_mb_me_ra_rb_rlwnm_rs_useStatus::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((((MB)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"rotlw");
	}else{
		index += sprintf (result + index,"rlwnm");
	}
	index += sprintf (result + index,".");
	index += sprintf (result + index," ");
	if(((((MB)==(0U)))&&(((ME)==(31U))))){
		index += sprintf (result + index,"r%u,r%u,r%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(rB)));
	}else{
		index += sprintf (result + index,"r%u,r%u,r%u,%u,%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(rB)),(u32)((u32)(MB)),(u32)((u32)(ME)));
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_mb_me_ra_rb_rlwnm_rs_useStatus)");
	#endif
	return result;
}

const char* const e200z4_noStatus_notaftercomplemented_notcomplemented_or_ra_rb_rs::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((rS)==(rB))){
		index += sprintf (result + index,"mr");
	}else{
		index += sprintf (result + index,"or");
	}
	if(((rS)==(rB))){
		index += sprintf (result + index," r%u,r%u",(u32)((u32)(rA)),(u32)((u32)(rS)));
	}else{
		index += sprintf (result + index," r%u,r%u,r%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(rB)));
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_noStatus_notaftercomplemented_notcomplemented_or_ra_rb_rs)");
	#endif
	return result;
}

const char* const e200z4_notaftercomplemented_notcomplemented_or_ra_rb_rs_useStatus::mnemo(){
	char *result = new char[128];
	int index = 0;
	if(((rS)==(rB))){
		index += sprintf (result + index,"mr");
	}else{
		index += sprintf (result + index,"or");
	}
	index += sprintf (result + index,".");
	if(((rS)==(rB))){
		index += sprintf (result + index," r%u,r%u",(u32)((u32)(rA)),(u32)((u32)(rS)));
	}else{
		index += sprintf (result + index," r%u,r%u,r%u",(u32)((u32)(rA)),(u32)((u32)(rS)),(u32)((u32)(rB)));
	}
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_notaftercomplemented_notcomplemented_or_ra_rb_rs_useStatus)");
	#endif
	return result;
}

const char* const e200z4_lt_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"lt");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_lt_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_imm_lt_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"lt");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_imm_lt_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_le_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"le");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_le_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_imm_le_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"le");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_imm_le_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_eq_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"eq");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_eq_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_eq_imm_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"eq");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_eq_imm_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_ge_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"ge");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_ge_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_ge_imm_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"ge");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_ge_imm_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_gt_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"gt");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_gt_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_gt_imm_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"gt");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_gt_imm_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_ne_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"ne");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_ne_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_imm_ne_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"ne");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_imm_ne_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_llt_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"llt");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_llt_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_imm_llt_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"llt");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_imm_llt_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_lle_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"lle");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_lle_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_imm_lle_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"lle");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_imm_lle_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_lge_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"lge");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_lge_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_imm_lge_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"lge");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_imm_lge_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_lgt_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"lgt");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"r%u",(u32)((u32)(rA)));
	index += sprintf (result + index,",");
	index += sprintf (result + index,"r%u",(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_lgt_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_imm_lgt_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"lgt");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"r%u,%d",(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_imm_lgt_ra_simm_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_notSimple_ra_rb_reg_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index," ");
	index += sprintf (result + index,"%u,r%u,r%u",(u32)((u32)(TO)),(u32)((u32)(rA)),(u32)((u32)(rB)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_notSimple_ra_rb_reg_to_f_tw)");
	#endif
	return result;
}

const char* const e200z4_imm_notSimple_ra_simm_to_f_tw::mnemo(){
	char *result = new char[128];
	int index = 0;
	index += sprintf (result + index,"tw");
	index += sprintf (result + index,"i ");
	index += sprintf (result + index,"%u,r%u,%d",(u32)((u32)(TO)),(u32)((u32)(rA)),(u32)((u32)(SIMM)));
	#ifdef DEBUG_MNEMO
		index += sprintf (result + index, " (e200z4_imm_notSimple_ra_simm_to_f_tw)");
	#endif
	return result;
}
