/**
 * generated by HARMLESS : 'Hardware ARchitecture Modeling Language
 *                          for Embedded Software Simulation'
 * model : e200z4
 *
 */

#include "instruction.h" //first for precompiled header
#include <iostream>
#include "arch.h"

using namespace std;

// instructions that require registers for the data dependency controller.

void e200z4_SP_Check_abs_b_li_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_f_nz_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_f_nz_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_f_revStatPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_f_statPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_noCond_nz_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_noCond_nz_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_noCond_revStatPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_noCond_statPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_nz_revStatPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_nz_statPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_revStatPred_t_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_statPred_t_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_f_nd_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_f_nd_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_nd_noCond_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_nd_noCond_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_nd_revStatPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_nd_statPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_f_nz_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_f_nz_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_f_revStatPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_f_statPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_noCond_nz_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_noCond_nz_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_noCond_revStatPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_noCond_statPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_nz_revStatPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_nz_statPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_revStatPred_t_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_d_statPred_t_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_f_nd_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_f_nd_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_nd_noCond_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_nd_noCond_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_nd_revStatPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_ctr_nd_statPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_f_nz_revStatPred_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_f_nz_statPred_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_f_revStatPred_tolr_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_f_statPred_tolr_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_noCond_nz_revStatPred_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_noCond_nz_statPred_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_noCond_revStatPred_tolr_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_noCond_statPred_tolr_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_nz_revStatPred_t_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_nz_statPred_t_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_revStatPred_t_tolr_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_d_statPred_t_tolr_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_f_nd_revStatPred_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_f_nd_statPred_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_nd_noCond_revStatPred_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_nd_noCond_statPred_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_nd_revStatPred_t_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_abs_bc_bi_bo_nd_statPred_t_tolr_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_b_li_rel_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_f_nz_rel_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_f_nz_rel_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_f_rel_revStatPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_f_rel_statPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_noCond_nz_rel_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_noCond_nz_rel_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_noCond_rel_revStatPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_noCond_rel_statPred_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_nz_rel_revStatPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_nz_rel_statPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_rel_revStatPred_t_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_d_rel_statPred_t_updatelr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_f_nd_rel_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_f_nd_rel_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_nd_noCond_rel_revStatPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_nd_noCond_rel_statPred_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_nd_rel_revStatPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_bc_bd_bi_bo_nd_rel_statPred_t_updatelr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_SP_Check_sc::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_b_li::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
}

void e200z4_abs_bc_bd_bi_bo_d_f_nz_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_f_nz_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_f_revStatPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_f_statPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_noCond_nz_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_noCond_nz_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_noCond_revStatPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_noCond_statPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_nz_revStatPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_nz_statPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_revStatPred_t_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_d_statPred_t_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_f_nd_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_f_nd_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_nd_noCond_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_nd_noCond_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_nd_revStatPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bd_bi_bo_nd_statPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_f_nz_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_f_nz_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_f_revStatPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_f_statPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_noCond_nz_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_noCond_nz_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_noCond_revStatPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_noCond_statPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_nz_revStatPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_nz_statPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_revStatPred_t_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_d_statPred_t_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_f_nd_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_f_nd_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_nd_noCond_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_nd_noCond_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_nd_revStatPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_ctr_nd_statPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_f_nz_revStatPred_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_f_nz_statPred_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_f_revStatPred_tolr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_f_statPred_tolr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_noCond_nz_revStatPred_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_noCond_nz_statPred_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_noCond_revStatPred_tolr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_noCond_statPred_tolr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_nz_revStatPred_t_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_nz_statPred_t_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_revStatPred_t_tolr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_d_statPred_t_tolr_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_f_nd_revStatPred_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_f_nd_statPred_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_nd_noCond_revStatPred_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_nd_noCond_statPred_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_nd_revStatPred_t_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_abs_bc_bi_bo_nd_statPred_t_tolr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_add_noOv_noStatus_ra_rb_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_add_noOv_noStatus_ra_rb_rd_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_add_noOv_ra_rb_rd_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_add_noOv_ra_rb_rd_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_add_noStatus_ra_rb_rd_useOv::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_add_noStatus_ra_rb_rd_useOv_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_add_ra_rb_rd_useOv_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_add_ra_rb_rd_useOv_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_adde_noOv_noStatus_ra_rb_rd_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_adde_noOv_ra_rb_rd_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_adde_noStatus_ra_rb_rd_useOv_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_adde_ra_rb_rd_useOv_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addi_noOv_noStatus_ra_rd_simm::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addic_noOv_noStatus_ra_rd_simm_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addic_noOv_ra_rd_simm_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addis_noOv_noStatus_ra_rd_simm::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addme_noOv_noStatus_ra_rd_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addme_noOv_ra_rd_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addme_noStatus_ra_rd_useOv_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addme_ra_rd_useOv_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addze_noOv_noStatus_ra_rd_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addze_noOv_ra_rd_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addze_noStatus_ra_rd_useOv_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_addze_ra_rd_useOv_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_aftercomplemented_and_noStatus_notcomplemented_ra_rb_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_aftercomplemented_and_notcomplemented_ra_rb_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_aftercomplemented_noStatus_notcomplemented_or_ra_rb_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_aftercomplemented_noStatus_notcomplemented_ra_rb_rs_xor::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_aftercomplemented_notcomplemented_or_ra_rb_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_aftercomplemented_notcomplemented_ra_rb_rs_useStatus_xor::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_algebraic_d_half_load_notu_ra_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_algebraic_d_half_load_ra_rd_u::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_algebraic_half_load_notu_ra_rb_rd_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_algebraic_half_load_ra_rb_rd_u_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_and_complemented_noStatus_notaftercomplemented_ra_rb_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_and_complemented_notaftercomplemented_ra_rb_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_and_noStatus_notaftercomplemented_notcomplemented_ra_rb_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_and_notaftercomplemented_notcomplemented_ra_rb_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_and_notaftercomplemented_notshifted_ra_rs_uimm_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_and_notaftercomplemented_ra_rs_shifted_uimm_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_arith_cmp_crfd_immediate_l_ra_simm::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_arith_cmp_crfd_l_ra_rb_reg::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_b_li_rel::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_f_nz_rel_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_f_nz_rel_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_f_rel_revStatPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_f_rel_statPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_noCond_nz_rel_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_noCond_nz_rel_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_noCond_rel_revStatPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_noCond_rel_statPred_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_nz_rel_revStatPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_nz_rel_statPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_rel_revStatPred_t_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_d_rel_statPred_t_z::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_f_nd_rel_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_f_nd_rel_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_nd_noCond_rel_revStatPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_nd_noCond_rel_statPred::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_nd_rel_revStatPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_bc_bd_bi_bo_nd_rel_statPred_t::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_br_half_load_notu_ra_rb_rd_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_br_half_notu_ra_rb_rs_store_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_br_load_notu_ra_rb_rd_word_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_br_notu_ra_rb_rs_store_word_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_byte_d_load_notu_ra_rd_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_byte_d_load_ra_rd_u_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_byte_d_notu_ra_rs_store::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_byte_d_ra_rs_store_u::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_byte_load_notu_ra_rb_rd_x_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_byte_load_ra_rb_rd_u_x_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_byte_notu_ra_rb_rs_store_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_byte_ra_rb_rs_store_u_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_cmp_crfd_immediate_l_logical_ra_uimm::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_cmp_crfd_l_logical_ra_rb_reg::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_cntlzw_noStatus_ra_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_cntlzw_ra_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_complemented_noStatus_notaftercomplemented_or_ra_rb_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_complemented_notaftercomplemented_or_ra_rb_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_crand_crba_crbb_crbd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crandc_crba_crbb_crbd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crba_crbb_crbd_creqv::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crba_crbb_crbd_crnand::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crba_crbb_crbd_crnor::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crba_crbb_crbd_cror::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crba_crbb_crbd_crorc::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crba_crbb_crbd_crxor::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crfd_crfs_mcrf::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crfd_mcrxr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}

void e200z4_crm_mtcrf_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_fd_frd_load_notu_ra::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileFSRU_FPRMaskRead<<14;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_fd_frd_load_ra_u::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileFSRU_FPRMaskRead<<14;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_fd_frs_notu_ra_store::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileFSRU_FPRMaskRead<<14;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_fd_frs_ra_store_u::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileFSRU_FPRMaskRead<<14;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_half_load_notu_ra_rd_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_half_load_ra_rd_u_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_half_notu_ra_rs_store::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_half_ra_rs_store_u::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_load_notu_ra_rd_word_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_load_ra_rd_u_word_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_mw_notu_ra_rs_store::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_notu_ra_rs_store_word::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_d_ra_rs_store_u_word::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_divw_noOv_noStatus_ra_rb_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_divw_noOv_ra_rb_rd_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_divw_noStatus_ra_rb_rd_useOv::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_divw_ra_rb_rd_useOv_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_divwu_noOv_noStatus_ra_rb_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_divwu_noOv_ra_rb_rd_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_divwu_noStatus_ra_rb_rd_useOv::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_divwu_ra_rb_rd_useOv_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_eq_imm_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_eq_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_extsb_noStatus_ra_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_extsb_ra_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_extsh_noStatus_ra_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_extsh_ra_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ge_imm_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ge_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_gt_imm_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_gt_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_half_load_notu_ra_rb_rd_x_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_half_load_ra_rb_rd_u_x_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_half_notu_ra_rb_rs_store_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_half_ra_rb_rs_store_u_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_imm_le_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_imm_lge_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_imm_lgt_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_imm_lle_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_imm_llt_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_imm_lt_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_imm_ne_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_imm_notSimple_ra_simm_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_le_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_lge_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_lgt_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_lle_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_llt_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_load_notu_ra_rb_rd_word_x_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_load_ra_rb_rd_u_word_x_zero::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_lt_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mb_me_noStatus_ra_rb_rlwnm_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mb_me_noStatus_ra_rlw_rlwimi_rs_sh::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mb_me_noStatus_ra_rlwinm_rs_sh::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mb_me_ra_rb_rlwnm_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mb_me_ra_rlw_rlwimi_rs_sh_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mb_me_ra_rlwinm_rs_sh_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mfcr_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mfmsr_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mfspr_rd_spr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mtmsr_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mtspr_rs_spr::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mulhw_noOv_noStatus_ra_rb_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mulhw_noOv_ra_rb_rd_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mulhwu_noOv_noStatus_ra_rb_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mulhwu_noOv_ra_rb_rd_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mulli_noOv_noStatus_ra_rd_simm::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mullw_noOv_noStatus_ra_rb_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mullw_noOv_ra_rb_rd_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mullw_noStatus_ra_rb_rd_useOv::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_mullw_ra_rb_rd_useOv_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ne_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_neg_noOv_noStatus_ra_rd::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_neg_noOv_ra_rd_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_neg_noStatus_ra_rd_useOv::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_neg_ra_rd_useOv_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_noStatus_ra_rb_rd_subf::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_noStatus_ra_rb_rd_subf_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_noStatus_ra_rb_rd_subfe_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_noStatus_ra_rd_simm_subfic_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_noStatus_ra_rd_subfme_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_noStatus_ra_rd_subfze_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_ra_rb_rd_subf_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_ra_rb_rd_subf_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_ra_rb_rd_subfe_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_ra_rd_subfme_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noOv_ra_rd_subfze_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_notaftercomplemented_notcomplemented_or_ra_rb_rs::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_notaftercomplemented_notcomplemented_ra_rb_rs_xor::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_notaftercomplemented_notshifted_or_ra_rs_uimm::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_notaftercomplemented_notshifted_ra_rs_uimm_xor::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_notaftercomplemented_or_ra_rs_shifted_uimm::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_notaftercomplemented_ra_rs_shifted_uimm_xor::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_ra_rb_rd_subf_useOv::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_ra_rb_rd_subf_useOv_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_ra_rb_rd_subfe_useOv_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_ra_rb_rs_slw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_ra_rb_rs_sraw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_ra_rb_rs_srw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_ra_rd_subfme_useOv_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_ra_rd_subfze_useOv_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_noStatus_ra_rs_sh_sraw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_notSimple_ra_rb_reg_to_f_tw::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_notaftercomplemented_notcomplemented_or_ra_rb_rs_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_notaftercomplemented_notcomplemented_ra_rb_rs_useStatus_xor::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_notu_ra_rb_rs_store_word_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rb_rd_subf_useOv_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rb_rd_subf_useOv_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rb_rd_subfe_useOv_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rb_rs_slw_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rb_rs_sraw_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rb_rs_srw_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rb_rs_store_u_word_x::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = 0;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rd_subfme_useOv_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rd_subfze_useOv_useStatus_withCarry::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_ra_rs_sh_sraw_useStatus::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
	regsMask0 |= m_DDCRegFileSRU_GPRMaskRead<<30;
}

void e200z4_rfi::getDDCReadRegs(u64 &regsMask0){
	regsMask0 = m_DDCRegMaskRead;
}
