/**
 * generated by HARMLESS : 'Hardware ARchitecture Modeling Language
 *                          for Embedded Software Simulation'
 * model : e200z4
 *
 */

#include "instruction.h" //first for precompiled headers
#include <stdio.h>
#include "macro.h"
#include "utils.h"

//instructions with a format... but no syntax defined
