/**
 * generated by HARMLESS : 'Hardware ARchitecture Modeling Language
 *                          for Embedded Software Simulation'
 * model : e200z4
 *
 */


#include "arch.h"
#include "instruction.h"

void e200z4_SP_Check_abs_b_li_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1295
	branch_inst_doJump = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1338
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->LI)<<((s32)(2U))),24U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_f_nz_revStatPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_f_nz_statPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_f_revStatPred_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_f_statPred_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_noCond_nz_revStatPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_noCond_nz_statPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_noCond_revStatPred_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_noCond_statPred_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_nz_revStatPred_t_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_nz_statPred_t_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_revStatPred_t_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_d_statPred_t_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_f_nd_revStatPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_f_nd_statPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_nd_noCond_revStatPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_nd_noCond_statPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_nd_revStatPred_t_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_abs_bc_bd_bi_bo_nd_statPred_t_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_b_li_rel_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1295
	branch_inst_doJump = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1338
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->LI)<<((s32)(2U))),24U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_f_nz_rel_revStatPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_f_nz_rel_statPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_f_rel_revStatPred_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_f_rel_statPred_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_noCond_nz_rel_revStatPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_noCond_nz_rel_statPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_noCond_rel_revStatPred_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_noCond_rel_statPred_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_nz_rel_revStatPred_t_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_nz_rel_statPred_t_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_rel_revStatPred_t_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_d_rel_statPred_t_updatelr_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_f_nd_rel_revStatPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_f_nd_rel_statPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_nd_noCond_rel_revStatPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_nd_noCond_rel_statPred_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_nd_rel_revStatPred_t_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_bc_bd_bi_bo_nd_rel_statPred_t_updatelr::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1358
	_arch->setLR(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_SP_Check_sc::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1693
	_arch->setSRR0(((_arch->PC())) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1694
	_arch->setSRR1(((((((_arch->SRR1()))&((u32)(((~2017460083U) & 0x7FFFFFFF)))))|((((((_arch->MSR()))&(2277572607U)))&((u32)(2017460083U)))))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1696
	_arch->setMSR(((((((_arch->MSR()))&(4294644684U)))|((u32)(((_arch->MSR_ILE())) & 0xFFFFFFFF)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1702
	u32 newPC = 3072U; // u32
	// 'ppc_e200z4.hadl', l.1702
	u8 cond = 1U; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_b_li::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1295
	branch_inst_doJump = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1338
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->LI)<<((s32)(2U))),24U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_f_nz_revStatPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_f_nz_statPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_f_revStatPred_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_f_statPred_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_noCond_nz_revStatPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_noCond_nz_statPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_noCond_revStatPred_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_noCond_statPred_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_nz_revStatPred_t::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_nz_statPred_t::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_revStatPred_t_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_d_statPred_t_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_f_nd_revStatPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_f_nd_statPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_nd_noCond_revStatPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_nd_noCond_statPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_nd_revStatPred_t::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_abs_bc_bd_bi_bo_nd_statPred_t::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1351
	branch_inst_target_address = (branch_inst_value) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_b_li_rel::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1295
	branch_inst_doJump = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1338
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->LI)<<((s32)(2U))),24U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_f_nz_rel_revStatPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_f_nz_rel_statPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_f_rel_revStatPred_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_f_rel_statPred_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_noCond_nz_rel_revStatPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_noCond_nz_rel_statPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_noCond_rel_revStatPred_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_noCond_rel_statPred_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_nz_rel_revStatPred_t::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_nz_rel_statPred_t::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_rel_revStatPred_t_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_d_rel_statPred_t_z::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1286
	_arch->setCTR(((((_arch->CTR()))-((u32)(1U)))) & 0xFFFFFFFF);

	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1310
	u8 behavior_case_126_ctr_ok; //u1
	// 'ppc_e200z4.hadl', l.1312
	behavior_case_126_ctr_ok = ((((((_arch->CTR()))!=(0U)))^(FIELD(this->BO,(1U),(1U))))) & 0x1;

	// 'ppc_e200z4.hadl', l.1313
	branch_inst_doJump = (((behavior_case_126_ctr_ok)&(behavior_case_120_cond_ok))) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_f_nd_rel_revStatPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_f_nd_rel_statPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1305
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(0U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_nd_noCond_rel_revStatPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_nd_noCond_rel_statPred::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1303
	behavior_case_120_cond_ok = (1U) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_nd_rel_revStatPred_t::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

void e200z4_bc_bd_bi_bo_nd_rel_statPred_t::detectBranch(arch *_arch){
	// 'ppc_e200z4.hadl', l.1293
	u8 branch_inst_doJump; //u1
	// 'ppc_e200z4.hadl', l.1300
	u8 behavior_case_120_cond_ok; //u1
	// 'ppc_e200z4.hadl', l.1304
	behavior_case_120_cond_ok = (((FIELD((_arch->CR()),(((31U)-(this->BI))),(((31U)-(this->BI)))))==(1U))) & 0x1;

	// 'ppc_e200z4.hadl', l.1315
	branch_inst_doJump = (behavior_case_120_cond_ok) & 0x1;

	// 'ppc_e200z4.hadl', l.1334
	u32 branch_inst_value; //u32
	// 'ppc_e200z4.hadl', l.1341
	branch_inst_value = ((u32)((s32)((SIGN_EXTEND(((this->BD)<<((s16)(2U))),14U,32U)) & 0xFFFFFFFF))) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1348
	u32 branch_inst_target_address; //u32
	// 'ppc_e200z4.hadl', l.1352
	branch_inst_target_address = ((u32)(((((((s64)(SIGN_EXTEND((s32)((_arch->PC())),32U,33U)))+((s64)(SIGN_EXTEND((s32)(branch_inst_value),32U,33U)))))-((s64)(SIGN_EXTEND(4U,4U,33U))))) & 0xFFFFFFFF)) & 0xFFFFFFFF;

	// 'ppc_e200z4.hadl', l.1365
	u32 newPC = branch_inst_target_address; // u32
	// 'ppc_e200z4.hadl', l.1365
	u8 cond = branch_inst_doJump; // u1
	// 'ppc_e200z4.hadl', l.43
	_arch->setPC((newPC) & 0xFFFFFFFF);
}

