/**
 * generated by HARMLESS : 'Hardware ARchitecture Modeling Language
 *                          for Embedded Software Simulation'
 * model : e200z4
 *
 */

#ifndef GADL_NO_ACTION

#include "peripherals.h"
#include "arch.h"

bool SERIAL0write::trigger(storage *, u8 , spyInfo *)
{
	// 'ppc_e200z4.hadl', l.167
	std::cerr << std::hex << (s8)(FIELD((m_arch->SERIAL0()),(7U),(0U)));
	return false;
}

#endif //GADL_NO_ACTION

