/**
 * generated by HARMLESS : 'Hardware ARchitecture Modeling Language
 *                          for Embedded Software Simulation'
 * model : e200z4
 *
 */

typedef u32 type_prgaddr;
typedef u16 type_sp;


#define TASK_UNKNOWN 0

