/**
 * generated by HARMLESS : 'Hardware ARchitecture Modeling Language
 *                          for Embedded Software Simulation'
 * model : e200z4
 *
 */

#ifndef __TIMING_SIGNAL_H__
#define __TIMING_SIGNAL_H__

#include <iostream>
#include "types.h"

#define NB_SIGNAL_WAIT 5
#define NB_SIGNAL_EMIT 4

#define SIGNAL_WAIT_ICache_OFFSET 1 
#define SIGNAL_WAIT_ICacheLineBuffer_OFFSET 2 
#define SIGNAL_WAIT_MemDev_OFFSET 4 
#define SIGNAL_EMIT_ICache_OFFSET 0 
#define SIGNAL_EMIT_ICacheLineBuffer_OFFSET 1 
#define SIGNAL_EMIT_MemDev_OFFSET 3 

#define SIGNAL_WAIT_ICacheE200Z4LineBuffer_fillBuffer 0 
#define SIGNAL_WAIT_ICacheE200Z4LineBuffer_memEnd 1 
#define SIGNAL_WAIT_ICacheE200Z4_bufferData 0 
#define SIGNAL_WAIT_mem_memStart 0 
#define SIGNAL_EMIT_ICacheE200Z4LineBuffer_bufferData 0 
#define SIGNAL_EMIT_ICacheE200Z4LineBuffer_memStart 1 
#define SIGNAL_EMIT_ICacheE200Z4_fillBuffer 0 
#define SIGNAL_EMIT_mem_memEnd 0 


extern const unsigned int signalLinksFrom[NB_SIGNAL_WAIT];
extern const unsigned int signalLinksTo[NB_SIGNAL_EMIT];

#endif // __TIMING_SIGNAL_H__
